### ISSUE TITLE
Load organization details -> Fails 

### ISSUE THREAD

**Issue by edifirut** [openline-ai/openline-customer-os#1485]
react-dom.development.js?ac89:22839 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#ABC' is not a valid selector.
    at Function.find (webpack-internal:///./node_modules/primereact/utils/utils.esm.js:399:43)
    at setEvent (webpack-internal:///./node_modules/primereact/tooltip/tooltip.esm.js:546:82)
    at setTargetEventOperations (webpack-internal:///./node_modules/primereact/tooltip/tooltip.esm.js:557:11)
    at loadTargetEvents (webpack-internal:///./node_modules/primereact/tooltip/tooltip.esm.js:531:5)
    at eval (webpack-internal:///./node_modules/primereact/tooltip/tooltip.esm.js:569:5)
    at commitHookEffectListMount (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23145:26)
    at commitPassiveMountOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24921:13)
    at commitPassiveMountEffects_complete (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24886:9)
    at commitPassiveMountEffects_begin (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24873:7)
    at commitPassiveMountEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24861:3)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27034:3)
    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26979:14)
    at commitRootImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26930:5)
    at commitRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26677:5)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26112:3)
    at flushSyncCallbacks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12042:22)
    at flushPassiveEffectsImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:27055:3)
    at flushPassiveEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26979:14)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26764:9)
    at workLoop (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:266:34)
    at flushWork (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:533:21)

**Comment by edifirut** [comment]
http://localhost:3001/organization/1dee098b-0190-49ec-a63c-adf09835ff4b

**Comment by edifirut** [comment]
resolved
